### ISSUE TITLE
Visualizzazione Layer Group Geologia

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#236]
### Description
Il layer group GEOLOGIA (GRUPPO) si visualizza correttamente nel layer preview ma non si vede in MapStore2

**Comment by MV88** [comment]
I tried to load other layer group with success.

it seems that the issue is on the data_dir of geoserver.
in particaulr doing this getMap request 

https://mappe.comune.genova.it/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=GEOLOGIA_GRUPPO&STYLES=&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&WIDTH=256&HEIGHT=256&BBOX=900122.445086237%2C5479006.187481433%2C939258.2035682473%2C5518141.945963443

we obtain this:
```
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc https://mappe.comune.genova.it:443/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">
  <ServiceException>
java.lang.IllegalStateException: Could not locate a layer or layer group with id LayerGroupInfoImpl-7176b72d:168a41427b4:-4953 within GeoServer configuration, the GWC configuration seems to be out of synch Could not locate a layer or layer group with id LayerGroupInfoImpl-7176b72d:168a41427b4:-4953 within GeoServer configuration, the GWC configuration seems to be out of synch
  </ServiceException>
</ServiceExceptionReport>
```

So probably one of the layer is not present anymore in the gwc configuration.
As a side effect i'm not able to enter the Tile Layers page

because of this 
`Could not locate a layer or layer group with id LayerGroupInfoImpl-7176b72d:168a41427b4`

**Comment by offtherailz** [comment]
Removing the 900913_comge  from the layer group configuration solved the problem. 

NOTE: It seems the `900913_comge` gridset, that doesn't exist anymore, appears in many layers. 
It doesn't seem to cause problem except for layer groups, anyway.
