### ISSUE TITLE
Query Panel issue 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#300]
### Description
There is a problem with a specific filter in query panel on layer SCUOLE.

*Steps to reproduce*

- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/26187) map 
- Select the layer SCUOLE and open the attribute table
- Open the advanced filter (query panel) and configure the folowing filter:
UNITA_URBANISTICA = 33 PRÈ
- Do a search

*Expected Result*

Both the map and attribute table are properly filtered

*Current Result*

Only the attribute table is properly filtered, the layer SCUOLE disappear from the map

### Other useful information (optional):
Other kind of filters seems to work fine, the problem seems to be related to the filter value **prè**

**Comment by offtherailz** [comment]
Accordingly to this Stack overflow question

https://stackoverflow.com/questions/14925073/how-to-find-out-running-tomcat-version

The problem is that tomcat 7 does not recognize utf-8 encoding in URLs.


[geosolutions@vm-linuxgeofetest lib]$ java -cp catalina.jar org.apache.catalina.util.ServerInfo
Server version: Apache Tomcat/7.0.76
Server built:   Mar 12 2019 10:11:36 UTC
Server number:  7.0.76.0
OS Name:        Linux
OS Version:     3.10.0-327.22.2.el7.x86_64
Architecture:   amd64
JVM Version:    1.8.0_121-b13
JVM Vendor:     Oracle Corporation

While tomcat8 uses it as default. 

We can fix it setting up tomcat's `server.xml` connector of GeoServer URIEncoding this way (both ajp and http connector tags) :
```
<Connector
  URIEncoding="UTF-8"
```

I did it in test and it works:

http://vm-linuxgeofetest.comune.genova.it/geoserver-test/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=SITGEO%3ASCUOLE_AGG_GEO&STYLES=&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=false&CQL_FILTER=(%22UNITA_URBANISTICA%22%3D%2733%20PR%C3%88%27)&WIDTH=1219&HEIGHT=922&BBOX=992873.4044317456%2C5529209.788793424%2C994329.2909548648%2C5530310.959732158

**Comment by randomorder** [comment]
@giacomoc92 please schedule this change with Tobia. It requires a Tomcat restart.
Remember to document this change in the installation doc of the machines

**Comment by randomorder** [comment]
It would be a good idea to do #291 first and check if the plugin is missing first and install the plugin and the same time to avoid another geoserver restart.

**Comment by giacomoc92** [comment]
> please schedule this change with Tobia. It requires a Tomcat restart.
Remember to document this change in the installation doc of the machines

@tdipisa what would be a good time to do this?

**Comment by tdipisa** [comment]
@randomorder @giacomoc92 this is still in backlog since we need to wait the MS project update (#301, that is in progress). I would like to finish and test this first before proceeding with other devops activities in client machines. I will move the devop issues in ready as soon as it is time to schedule them.

**Comment by randomorder** [comment]
ok, I am moving the issue in backlog in the DevOps board

**Comment by randomorder** [comment]
applied in PROD for Master and Both Slaves. Please test
