### ISSUE TITLE
Massive SRS Update of GeoServer Layers

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#332]
### Description
The client started the conversion of the cartografy to EPSG:7791 (also through IGM grids and semi automatic ogr2ogr scripts.
The problem is related to layers already existing in GeoServer for which there are a lot of XML files to update (more or less layers are 371).
A batch process is needed here (if possible) for a massive update of layers configuration files in GeoServer to the new SRS.

**Comment by tdipisa** [comment]
The list of needed activities below:

- [ ] Batch script using [gs-config](https://github.com/geosolutions-it/gsconfig) using a geoserver local instance (if possible with some client's data in DB). **Still to check the best way to recalculate the layer extent and the related effort**.
- [ ] If possible align the client's GS test instance to the prod one
- [ ] Backup of the gs data dir in test
- [ ] Test the script in the client's test environment
- [ ] Backup of the gs data dir in prod
- [ ] Run the script in prod environment.

**Comment by afabiani** [comment]
@tdipisa in order to be sure the automatic procedure will work, I need to test the following scenario:

1. Create a layer on GeoServer based on a DB table (native CRS "x")
2. Update the data on the DB by changing the geometries (native CRS "y")
3. Create a simple script that forces a layer configuration update by using gsconfig REST library

(Same for the rasters by changing the original GeoTIFF)

That would need more or less 0.5 days to test it completely.

**Comment by tdipisa** [comment]
I suggested to the client to change the layers configurations one by one **after** the data update to avoid inconsistencies in a system that is already in PROD: an automatic script is not so useful in this case.
