### ISSUE TITLE
Enable the Visual style editor (Test Env)

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#427]
### Description
The client requested to enable the Visual Stile Editor in the MS version we have recently installed.
We have to proceed first on enabling this in Test environment and do some funcitonal tests to see if further actions are necessary.

**Comment by MV88** [comment]
StyleEditor Plugin and Thematic Layer plugin are competing for being the style editing plugin

this is decided [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/tocitemssettings/defaultSettingsTabs.js#L147-L210)

if both are present in localConfig, the ThematicLayer plugin wins

So in order to enable the StyleEditor Plugin we need to deactivate the ThematicLayer one because
they are mutually exclusive

**Comment by tdipisa** [comment]
@MV88 we agreed with the client to enable the visual style editor in test environment. Please enable it in test without versioning the config change it in master branch for the moment.

**Comment by tdipisa** [comment]
Dedicated context for the style editor in test environment available here:
http://vm-linuxgeofetest.comune.genova.it/MapStore2/#/context/StyleEditor
