### ISSUE TITLE
Attribute Table - Synch Map

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#457]
### Description
- [x] **Attribute Table - Synch Map**
For the C040 project, the [Synch Map tool](https://mapstore.readthedocs.io/en/v2021.01.03/user-guide/attributes-table/#set-filters) in the attribute table must be active by default. We have to externalize the config property for this to be able to tune it from localConfig.

**Comment by ElenaGallo** [comment]
@MV88 the Synch Map button is not active for the layers just added to the map (not yet saved in the map)

**How to Reproduce**
- Open a map
- Click on Burger Menu > Catalog
- Add a layer 
- Select a layer on TOC
- Click on Attribute Table

**Current Result**
The Synch Map button is not active

**Comment by tdipisa** [comment]
The above is true: you have to save the map and reload it to have the Synch Map working as expected while opening the Attribute Table. That's strange, any idea @MV88?

**Comment by MV88** [comment]
@tdipisa @ElenaGallo 
there is no need to add new layer, it is enough to reopen the feature grid
this happens by design after this comment https://github.com/geosolutions-it/MapStore2/issues/6076#issuecomment-719458871

**Explanation:**
The flag isSyncActive is stored in the application state and it is initialized here props
https://github.com/geosolutions-it/MapStore2/blob/fbcf72c68776f2b51f7a16e907498ba36ef9c1a9/web/client/plugins/FeatureEditor.jsx#L272-L278

when the feature grid is closed the value of this flag is set to false here
https://github.com/geosolutions-it/MapStore2/blob/fbcf72c68776f2b51f7a16e907498ba36ef9c1a9/web/client/epics/featuregrid.js#L1073-L1078

@offtherailz the weird thing is that componentDidMount is only executed once, and when the feature editor is closed is not unmounted

**Proposal:**
My idea would be to add the same if used in the did mount also here 
https://github.com/geosolutions-it/MapStore2/blob/fbcf72c68776f2b51f7a16e907498ba36ef9c1a9/web/client/plugins/FeatureEditor.jsx#L282-L289

in this way when the feature grid opens that flag is set to true (if configured so, i.e. by putting enableMapFilterSync to true in localConfig )

OR

we can keep this as is

OR

we change the epic by adding a check also for enableMapFilterSync

**Comment by MV88** [comment]
As agreed with @tdipisa if the flag is set to true we always enable map sync when the attribute table is opened
