### ISSUE TITLE
Failing FeatureInfo in GeoCollect on test environment

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#503]
### Description
See this test run: 
[A few sentences describing the overall goals of the issue.
](https://studio.cucumber.io/projects/47740/test-runs/617516/folder-snapshots/6277770/scenario-snapshots/21997040/test-snapshots/30147233)

Check if a problem of the test environment or what. (white response from the proxy).

**Comment by tdipisa** [comment]
@randomorder from what I can see by performing the request from the command line of the test machine, it seems a certificate issue with the geosollect.geosolutions server.

![image](https://user-images.githubusercontent.com/1280027/144881196-dd8d81f7-f73f-4832-9204-8504726e288f.png)

**Comment by randomorder** [comment]
There's a problem with SSL but it's on the client side

The certificate itself is ok but old operating systems and applications are Not going to recognize it as a valid certificate
![image](https://user-images.githubusercontent.com/5264230/144891809-ed857530-b269-4150-9133-3c5572fabb1d.png)

It's been issues by Let'sencrypt and there are breaking changes with old client applications...

How to move on, vairous options:
1 - Update the packages and JDK of the comuneGE machines
2 - Use a regular certificate for GCollect instead of the one issued by Let'sencrypt
3 - stop using GeoCollect

Easiest / quickest probably point 2

**Comment by randomorder** [comment]
2 hours. No, it's on the geocollect machine

**Comment by tdipisa** [comment]
thank you @randomorder. Please let me know when you can do that because I need to plan the release in production.

**Comment by randomorder** [comment]
this is on the geocollect side, should not be a blocker for the release

Next week I would say

**Comment by tdipisa** [comment]
> this is on the geocollect side, should not be a blocker for the release
> 
> Next week I would say

Yes, indeed. Next week is fine I think. I only would like to coordinate both well

**Comment by tdipisa** [comment]
@randomorder when you can proceed with this?

**Comment by randomorder** [comment]
Early next week. I'll keep you posted

**Comment by tdipisa** [comment]
Thank you @randomorder

**Comment by PabloBaronetti** [comment]
Hello @randomorder @tdipisa 

I changed the certificate, can you please try again to see if the error continues?

Thank you!

**Comment by tdipisa** [comment]
@PabloBaronetti thank you. It is working now.
