### ISSUE TITLE
Warning message during MS updates/maintainance

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#507]
It is requested by the client to show a configurable message in MS home page and inside each map/dashboard/geostory to notify users during application update and/or maintenance activities.

Something very basic like a permanent tooltip somewhere that can be disabled when done with maintenance activities.

Below is the text the client wants to show:
"_Gentile utente, dal 15/12/21 h 14.00 al 18/12/21 h 19.00 si potranno riscontrare alcuni disservizi del sistema.
Verrà effettuato un aggiornamento dell'Infrastruttura Dati Territoriali e aggiunte nuove funzionalità, il tutto finalizzato a migliorare il servizio pubblico. Ci scusiamo per i possibili inconvenienti. Ufficio S.I.T._"

**Comment by tdipisa** [comment]
@MV88 can you please do a quick evaluation/estimate of this task?

**Comment by MV88** [comment]
We can create custom plugin called **Maintenance** for this project
that can be placed inside "common" array so this will be visible everywhere

we can then show a permanent message and since the application must be usable we can put it:
- in the header of home, user admin, dashboard or geostory pages
![image](https://user-images.githubusercontent.com/11991428/145046313-850b3246-b5bb-4ff4-b689-22b630440455.png)

- in the footer of the map viewer (or in the same position of the header but with a background behind it)

it should not be too big this message to exceed current space available (heigth of header)


a couple 
- **active** if true it will show the plugin
- **messageId** this should refer to some locale messages that can contains some html  so [HTML](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/I18N/HTML.jsx) component can be used here)


alternatively we can remove active and if present it will render otherwise not

**Comment by tdipisa** [comment]
@alexander-fedorenko we need this max by end Monday Dec 13. @offtherailz will follow you on this.

**Comment by offtherailz** [comment]
The info provided by Matteo are good. I modified it a little bit. 
The plugin should be developed in c040 repository, under `js/plugins` and configured in `localConfig.json` for the home page with `enabled: false.`

**Comment by offtherailz** [comment]
Deployed in test @tdipisa
@ElenaGallo, could you please test this on test instance ? Thank you

**Comment by tdipisa** [comment]
@offtherailz tested and ok. We only missed to update the README file as I requested to you to document the related configuration to take into account during prod deploys.

**Comment by tdipisa** [comment]
> @offtherailz tested and ok. We only missed to update the README file as I requested to you to document the related configuration to take into account during prod deploys.

@alexander-fedorenko can you please do this?

**Comment by alexander-fedorenko** [comment]
@tdipisa Added paragraph into README,md
@offtherailz Please review.
https://github.com/geosolutions-it/MapStore2-C040/pull/509
