### ISSUE TITLE
Exception raised loading ca-dataset/tileset layer

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#563]
## Description

The client is asking to investigate why the following 3D Tiles:
https://www.cityexplorer3d.com/tourism/ca-dataset/tileset.json 

is raising an exception in MS:
![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/012f42b0-ce30-4fe9-b6cb-c2559edc4385)

## How to reproduce

-  Open the catalog tool and add the provided 3D tiles in Cesium map
- Ensure to zoom to Cagliari city

*Expected Result*

It should be possible to navigate the 3D layer without an exception

*Current Result*

The exception above is raised playing with the cesium map (pan/zoom) after some time.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by allyoucanmap** [comment]
# Issue

The provided tileset.json is composed by a pyramid of tilesets and some of them contains bounding volume region with invalid exent where the minimun x is equal to maximum x and the minimum y is equal to the minimum y (this happens when the camera is at building level). This is causing a wrong computation of the vector representing the bounding box of the tile and the consequential error that stop the rendering.

# Solution

Provide tilesets with valid bounding volume regions where the limit value on the x and y axis are not the same.
See specification https://github.com/CesiumGS/3d-tiles/tree/1.0/specification#region

# Investigation

We verified if the issue was caused by the mapstore implementation of the viewer or if was Cesium side so we used the Cesium sandcastle page and tested the tileset and we got same error

https://sandcastle.cesium.com/

```js
const viewer = new Cesium.Viewer("cesiumContainer", {
  shadows: true,
});

viewer.scene.globe.depthTestAgainstTerrain = true;

const viewModel = {
  height: 0,
};


const tileset = new Cesium.Cesium3DTileset({
  url: "https://www.cityexplorer3d.com/tourism/ca-dataset/tileset.json",
});

tileset.readyPromise
  .then(function (tileset) {
    viewer.scene.primitives.add(tileset);
    viewer.zoomTo(
      tileset,
      new Cesium.HeadingPitchRange(
        0.0,
        -0.5,
        tileset.boundingSphere.radius * 2.0
      )
    );
  })
  .catch(function (error) {
    console.log(error);
  });

```

![image](https://user-images.githubusercontent.com/19175505/162403997-74136004-854c-4b08-92f4-0e596318b98f.png)

We noticed also there were additional tilesets request part of the pyramid

````
A 3D tile failed to load: https://www.cityexplorer3d.com/tourism/ca-dataset/Tile-14-15-1-1/tileset.json
Error: normalized result is not a number
A 3D tile failed to load: https://www.cityexplorer3d.com/tourism/ca-dataset/Tile-15-17-1-1/tileset.json
Error: normalized result is not a number
A 3D tile failed to load: https://www.cityexplorer3d.com/tourism/ca-dataset/Tile-14-16-1-1/tileset.json
Error: normalized result is not a number
A 3D tile failed to load: https://www.cityexplorer3d.com/tourism/ca-dataset/Tile-14-14-1-1/tileset.json
Error: normalized result is not a number
A 3D tile failed to load: https://www.cityexplorer3d.com/tourism/ca-dataset/Tile-15-14-1-1/tileset.json
Error: normalized result is not a number
````

so we tried to access one of there tileset directly and we got a different error that was showing something wrong in the tile region computation

https://www.cityexplorer3d.com/tourism/ca-dataset/Tile-14-15-1-1/tileset.json

![image](https://user-images.githubusercontent.com/19175505/162404531-e7770a0c-3b49-4d4b-b171-1f461923525a.png)

```
DeveloperError: normalized result is not a number
Error
    at new DeveloperError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:83:13)
    at Function.Cartesian3.normalize (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:2126:13)
    at computeBox (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:217978:39)
    at new TileBoundingRegion (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:217867:5)
    at createRegion (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:220882:12)
    at Cesium3DTile.createBoundingVolume (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:220941:14)
    at new Cesium3DTile (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:219353:33)
    at makeTile (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:225514:12)
    at Cesium3DTileset.loadTileset (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:225435:29)
    at https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:224314:27
```

we tried to intercept the tileset json response and we noticed that some region extent had x and y limits whit same value meaning the region has a width and height equal to 0

`[minx, miny, maxx, maxy, minimum height, maximum height]`

![image](https://user-images.githubusercontent.com/19175505/162406079-c60bf6e1-8498-4953-ab60-4fb3a428dfda.png)

to confirm that those were causing the issue we apply on the fly a small delta value when a region was incorrect to validate it

`[minx - delta, miny - delta, maxx + delta, maxy + delta, minimum height, maximum height]`

and we finally got a working tileset (this is one of the sub tileset in the pyramid that was causing the error)

![image](https://user-images.githubusercontent.com/19175505/162407133-2791b8e4-9b71-4d37-9ec1-79e520af3eff.png)

# Additional notes

- there were other warning related to the tileset.json configuration. These are not causing issue but they are not aligned with the 1.0 specification
```
This tile uses a lowercase refine "replace". Instead use "REPLACE".
This tileset JSON uses the "content.url" property which has been deprecated. Use "content.uri" instead.
```
