### ISSUE TITLE
Statistical Query Engine: WPS

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#92]
**Rendering Transformation Aggregate WPS**: The aggregate WPS process should be extended (or another one created for the purpose) to aggregate on spatial entities; these will be used for thematic maps. The idea is to create a WPS to use as Rendering Transformation or By Itself, that aggregates geometries, adding an attribute with aggregation result. This can be used for styling and to create tables/charts with data.

**Comment by mbarto** [comment]
We need to chain different processes acting on a basic WFS query:
 * the WFS query will do the join between the involved tables: WFS 2.0 explicitly support joining on features, while WFS 1 can be tricked to support it (both only if features are coming from the same JDBC datastore); we currently have some issues:
    - WFS 2.0 queries cannot be used with WPS, so either we implement support or fallback to using WFS 1
    - WFS 1 does not support aliasing the features, but a default alias of a and b can be used, so no problem after all
    - join type is always INNER while we need LEFT: to support it we need work on GT and GS to add a new joinTypes param to the WFS Query tag
 * we need a WPS process to flatten the query result (so that attributes from both joined tables are returned as attributes of the resulting SimpleFeatureCollection)
 * we can use the Aggregate WPS process to do aggregation on the joined query (Sum, Count, etc.)
    - the result is not usable as is, we need to convert it to a SimpleFeatureCollection: we can use a PPIO (not sure if we can then chain this to another process, need to check), or have an AggregateProcess that directly produces SimpleFeatureCollection(s)

Summarizing, what is needed:
 * [ ] implement jointype support in WFS Query (INNER, OUTER)
 * [ ] implement SimpleFeatureCollection output for Aggregate
 * [ ] eventually implement support for WFS 2.0 queries as WPS input

**Comment by mbarto** [comment]
Partial work:
 * https://github.com/mbarto/geotools/tree/wps_join
 * https://github.com/mbarto/geoserver/tree/wps_join

**Comment by tdipisa** [comment]
Closed in favour of #90 using SQL views, proposal [here](https://docs.google.com/document/d/1lPKksL2_f3Ao4HFMIHpJbKn_9wTMzf_1bR1BVbENyfQ/edit)
